# Generated by Django 3.2 on 2022-01-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPosts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(default=None, max_length=50)),
                ('Name', models.CharField(default=None, max_length=50)),
                ('author', models.CharField(default=None, max_length=50)),
                ('content', models.TextField(default=None)),
                ('date', models.DateField(auto_now_add=True)),
                ('img1', models.ImageField(upload_to='images')),
            ],
        ),
    ]
