# Generated by Django 3.2 on 2022-02-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockpost', '0003_postcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
