# Generated by Django 3.2 on 2022-03-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpost', '0004_delete_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockposts',
            name='img1',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
