# Generated by Django 3.2 on 2022-03-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockpost', '0006_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='comments',
            name='post_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
