# Generated by Django 3.2 on 2022-03-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockpost', '0007_auto_20220314_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockposts',
            options={'verbose_name_plural': 'Stock Posts'},
        ),
    ]
